version: "3.3"

#Docker Networks
networks:
  local:
    driver: bridge

services:

  # Php composer service
  composer:
    image: composer:2.0
    container_name: composer

    command: ["composer", "install"]
    working_dir: /var/www
    volumes:
      - //DATA/tester:/var/www
    networks:
      - local
    depends_on:
      - tester

  # Node package manager service
  npm:
    image: node:14.13
    container_name: npm
    working_dir: /var/www/tester
    volumes:
      - //DATA:/var/www
    entrypoint: ["npm"] 

  # Webserver service
  nginx:
    image: nginx:1.18
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - //DATA:/var/www
      - //DATA/tester/docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
      - //DATA/tester/docker/nginx/tester.conf:/etc/nginx/conf.d/tester.conf
      - //DATA/tester/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - local

  # App service
  tester:
    image: tester:1.0
    build:
      context: ./docker/php/7.3-fpm
      dockerfile: Dockerfile
    container_name: tester
    env_file: ".env"
    restart: unless-stopped
    tty: true
    working_dir: /var/www/tester
    volumes:
      - //DATA:/var/www
    networks:
      - local
    depends_on:
      - nginx